;jhon
( println "Programa para hacer si una cadena es palindroma" )
( def palabra "RECONOCER" )
( def palindroma true )
( def j 8 )
( def i 0 )
( while (< i (/ 9 2) )
    ( if (not= (get palabra i) (get palabra j) )
        ( def palindroma false )
    )
    (def i (+ i 1))
    (def j (- j 1))
)
(def respuesta "")
( if (= palindroma true)
    (def respuesta "SI")
    (def respuesta "NO")
)
( println "Es palindroma " palabra " :" respuesta )
